/**
 */
package modeloER.provider;

import java.util.ArrayList;
import java.util.Collection;

import modeloER.util.ModeloERAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModeloERItemProviderAdapterFactory extends ModeloERAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ModeloERItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.Entidad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadItemProvider entidadItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.Entidad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadAdapter() {
		if (entidadItemProvider == null) {
			entidadItemProvider = new EntidadItemProvider(this);
		}

		return entidadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.Atributo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoItemProvider atributoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.Atributo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoAdapter() {
		if (atributoItemProvider == null) {
			atributoItemProvider = new AtributoItemProvider(this);
		}

		return atributoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.Relacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionItemProvider relacionItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.Relacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionAdapter() {
		if (relacionItemProvider == null) {
			relacionItemProvider = new RelacionItemProvider(this);
		}

		return relacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.Diagrama} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiagramaItemProvider diagramaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.Diagrama}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiagramaAdapter() {
		if (diagramaItemProvider == null) {
			diagramaItemProvider = new DiagramaItemProvider(this);
		}

		return diagramaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.EntidadRelacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionItemProvider entidadRelacionItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.EntidadRelacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionAdapter() {
		if (entidadRelacionItemProvider == null) {
			entidadRelacionItemProvider = new EntidadRelacionItemProvider(this);
		}

		return entidadRelacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.Herencia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HerenciaItemProvider herenciaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.Herencia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHerenciaAdapter() {
		if (herenciaItemProvider == null) {
			herenciaItemProvider = new HerenciaItemProvider(this);
		}

		return herenciaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.AtributoDerivado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoDerivadoItemProvider atributoDerivadoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.AtributoDerivado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoDerivadoAdapter() {
		if (atributoDerivadoItemProvider == null) {
			atributoDerivadoItemProvider = new AtributoDerivadoItemProvider(this);
		}

		return atributoDerivadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.AtributoMultivaluado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoMultivaluadoItemProvider atributoMultivaluadoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.AtributoMultivaluado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoMultivaluadoAdapter() {
		if (atributoMultivaluadoItemProvider == null) {
			atributoMultivaluadoItemProvider = new AtributoMultivaluadoItemProvider(this);
		}

		return atributoMultivaluadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.ClavePrimaria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClavePrimariaItemProvider clavePrimariaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.ClavePrimaria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClavePrimariaAdapter() {
		if (clavePrimariaItemProvider == null) {
			clavePrimariaItemProvider = new ClavePrimariaItemProvider(this);
		}

		return clavePrimariaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.ClaveForanea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClaveForaneaItemProvider claveForaneaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.ClaveForanea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClaveForaneaAdapter() {
		if (claveForaneaItemProvider == null) {
			claveForaneaItemProvider = new ClaveForaneaItemProvider(this);
		}

		return claveForaneaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.ClavePrimariaForanea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClavePrimariaForaneaItemProvider clavePrimariaForaneaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.ClavePrimariaForanea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClavePrimariaForaneaAdapter() {
		if (clavePrimariaForaneaItemProvider == null) {
			clavePrimariaForaneaItemProvider = new ClavePrimariaForaneaItemProvider(this);
		}

		return clavePrimariaForaneaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.TipoDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TipoDebilItemProvider tipoDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.TipoDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTipoDebilAdapter() {
		if (tipoDebilItemProvider == null) {
			tipoDebilItemProvider = new TipoDebilItemProvider(this);
		}

		return tipoDebilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.TipoFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TipoFuerteItemProvider tipoFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.TipoFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTipoFuerteAdapter() {
		if (tipoFuerteItemProvider == null) {
			tipoFuerteItemProvider = new TipoFuerteItemProvider(this);
		}

		return tipoFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.EntidadRelacionDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionDebilItemProvider entidadRelacionDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.EntidadRelacionDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionDebilAdapter() {
		if (entidadRelacionDebilItemProvider == null) {
			entidadRelacionDebilItemProvider = new EntidadRelacionDebilItemProvider(this);
		}

		return entidadRelacionDebilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.EntidadRelacionFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionFuerteItemProvider entidadRelacionFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.EntidadRelacionFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionFuerteAdapter() {
		if (entidadRelacionFuerteItemProvider == null) {
			entidadRelacionFuerteItemProvider = new EntidadRelacionFuerteItemProvider(this);
		}

		return entidadRelacionFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.AtributoDerivadoClavePrimaria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoDerivadoClavePrimariaItemProvider atributoDerivadoClavePrimariaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.AtributoDerivadoClavePrimaria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoDerivadoClavePrimariaAdapter() {
		if (atributoDerivadoClavePrimariaItemProvider == null) {
			atributoDerivadoClavePrimariaItemProvider = new AtributoDerivadoClavePrimariaItemProvider(this);
		}

		return atributoDerivadoClavePrimariaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.EntidadFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadFuerteItemProvider entidadFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.EntidadFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadFuerteAdapter() {
		if (entidadFuerteItemProvider == null) {
			entidadFuerteItemProvider = new EntidadFuerteItemProvider(this);
		}

		return entidadFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.EntidadDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadDebilItemProvider entidadDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.EntidadDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadDebilAdapter() {
		if (entidadDebilItemProvider == null) {
			entidadDebilItemProvider = new EntidadDebilItemProvider(this);
		}

		return entidadDebilItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (entidadItemProvider != null) entidadItemProvider.dispose();
		if (atributoItemProvider != null) atributoItemProvider.dispose();
		if (relacionItemProvider != null) relacionItemProvider.dispose();
		if (diagramaItemProvider != null) diagramaItemProvider.dispose();
		if (entidadRelacionItemProvider != null) entidadRelacionItemProvider.dispose();
		if (herenciaItemProvider != null) herenciaItemProvider.dispose();
		if (atributoDerivadoItemProvider != null) atributoDerivadoItemProvider.dispose();
		if (atributoMultivaluadoItemProvider != null) atributoMultivaluadoItemProvider.dispose();
		if (clavePrimariaItemProvider != null) clavePrimariaItemProvider.dispose();
		if (claveForaneaItemProvider != null) claveForaneaItemProvider.dispose();
		if (clavePrimariaForaneaItemProvider != null) clavePrimariaForaneaItemProvider.dispose();
		if (tipoDebilItemProvider != null) tipoDebilItemProvider.dispose();
		if (tipoFuerteItemProvider != null) tipoFuerteItemProvider.dispose();
		if (entidadRelacionDebilItemProvider != null) entidadRelacionDebilItemProvider.dispose();
		if (entidadRelacionFuerteItemProvider != null) entidadRelacionFuerteItemProvider.dispose();
		if (atributoDerivadoClavePrimariaItemProvider != null) atributoDerivadoClavePrimariaItemProvider.dispose();
		if (entidadFuerteItemProvider != null) entidadFuerteItemProvider.dispose();
		if (entidadDebilItemProvider != null) entidadDebilItemProvider.dispose();
	}

}
