/**
 */
package modeloER.modeloER.provider;

import java.util.ArrayList;
import java.util.Collection;

import modeloER.modeloER.util.ModeloERAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModeloERItemProviderAdapterFactory extends ModeloERAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ModeloERItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.Entidad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadItemProvider entidadItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.Entidad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadAdapter() {
		if (entidadItemProvider == null) {
			entidadItemProvider = new EntidadItemProvider(this);
		}

		return entidadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.Atributo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoItemProvider atributoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.Atributo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoAdapter() {
		if (atributoItemProvider == null) {
			atributoItemProvider = new AtributoItemProvider(this);
		}

		return atributoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.Relacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionItemProvider relacionItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.Relacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionAdapter() {
		if (relacionItemProvider == null) {
			relacionItemProvider = new RelacionItemProvider(this);
		}

		return relacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.Diagrama} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiagramaItemProvider diagramaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.Diagrama}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiagramaAdapter() {
		if (diagramaItemProvider == null) {
			diagramaItemProvider = new DiagramaItemProvider(this);
		}

		return diagramaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.EntidadRelacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionItemProvider entidadRelacionItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.EntidadRelacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionAdapter() {
		if (entidadRelacionItemProvider == null) {
			entidadRelacionItemProvider = new EntidadRelacionItemProvider(this);
		}

		return entidadRelacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.Herencia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HerenciaItemProvider herenciaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.Herencia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHerenciaAdapter() {
		if (herenciaItemProvider == null) {
			herenciaItemProvider = new HerenciaItemProvider(this);
		}

		return herenciaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoDerivado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoDerivadoItemProvider atributoDerivadoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoDerivado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoDerivadoAdapter() {
		if (atributoDerivadoItemProvider == null) {
			atributoDerivadoItemProvider = new AtributoDerivadoItemProvider(this);
		}

		return atributoDerivadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoMultivaluado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoMultivaluadoItemProvider atributoMultivaluadoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoMultivaluado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoMultivaluadoAdapter() {
		if (atributoMultivaluadoItemProvider == null) {
			atributoMultivaluadoItemProvider = new AtributoMultivaluadoItemProvider(this);
		}

		return atributoMultivaluadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.ClavePrimaria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClavePrimariaItemProvider clavePrimariaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.ClavePrimaria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClavePrimariaAdapter() {
		if (clavePrimariaItemProvider == null) {
			clavePrimariaItemProvider = new ClavePrimariaItemProvider(this);
		}

		return clavePrimariaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.ClaveForanea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClaveForaneaItemProvider claveForaneaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.ClaveForanea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClaveForaneaAdapter() {
		if (claveForaneaItemProvider == null) {
			claveForaneaItemProvider = new ClaveForaneaItemProvider(this);
		}

		return claveForaneaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.ClavePrimariaForanea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClavePrimariaForaneaItemProvider clavePrimariaForaneaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.ClavePrimariaForanea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClavePrimariaForaneaAdapter() {
		if (clavePrimariaForaneaItemProvider == null) {
			clavePrimariaForaneaItemProvider = new ClavePrimariaForaneaItemProvider(this);
		}

		return clavePrimariaForaneaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.RelacionTipoDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionTipoDebilItemProvider relacionTipoDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.RelacionTipoDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionTipoDebilAdapter() {
		if (relacionTipoDebilItemProvider == null) {
			relacionTipoDebilItemProvider = new RelacionTipoDebilItemProvider(this);
		}

		return relacionTipoDebilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.RelacionTipoFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionTipoFuerteItemProvider relacionTipoFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.RelacionTipoFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionTipoFuerteAdapter() {
		if (relacionTipoFuerteItemProvider == null) {
			relacionTipoFuerteItemProvider = new RelacionTipoFuerteItemProvider(this);
		}

		return relacionTipoFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.EntidadRelacionDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionDebilItemProvider entidadRelacionDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.EntidadRelacionDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionDebilAdapter() {
		if (entidadRelacionDebilItemProvider == null) {
			entidadRelacionDebilItemProvider = new EntidadRelacionDebilItemProvider(this);
		}

		return entidadRelacionDebilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.EntidadRelacionFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadRelacionFuerteItemProvider entidadRelacionFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.EntidadRelacionFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadRelacionFuerteAdapter() {
		if (entidadRelacionFuerteItemProvider == null) {
			entidadRelacionFuerteItemProvider = new EntidadRelacionFuerteItemProvider(this);
		}

		return entidadRelacionFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoDerivadoClavePrimaria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoDerivadoClavePrimariaItemProvider atributoDerivadoClavePrimariaItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoDerivadoClavePrimaria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoDerivadoClavePrimariaAdapter() {
		if (atributoDerivadoClavePrimariaItemProvider == null) {
			atributoDerivadoClavePrimariaItemProvider = new AtributoDerivadoClavePrimariaItemProvider(this);
		}

		return atributoDerivadoClavePrimariaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.EntidadFuerte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadFuerteItemProvider entidadFuerteItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.EntidadFuerte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadFuerteAdapter() {
		if (entidadFuerteItemProvider == null) {
			entidadFuerteItemProvider = new EntidadFuerteItemProvider(this);
		}

		return entidadFuerteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.EntidadDebil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadDebilItemProvider entidadDebilItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.EntidadDebil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadDebilAdapter() {
		if (entidadDebilItemProvider == null) {
			entidadDebilItemProvider = new EntidadDebilItemProvider(this);
		}

		return entidadDebilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoSimple} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoSimpleItemProvider atributoSimpleItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoSimple}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoSimpleAdapter() {
		if (atributoSimpleItemProvider == null) {
			atributoSimpleItemProvider = new AtributoSimpleItemProvider(this);
		}

		return atributoSimpleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoCompuesto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoCompuestoItemProvider atributoCompuestoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoCompuesto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoCompuestoAdapter() {
		if (atributoCompuestoItemProvider == null) {
			atributoCompuestoItemProvider = new AtributoCompuestoItemProvider(this);
		}

		return atributoCompuestoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.LinkASAC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkASACItemProvider linkASACItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.LinkASAC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkASACAdapter() {
		if (linkASACItemProvider == null) {
			linkASACItemProvider = new LinkASACItemProvider(this);
		}

		return linkASACItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoEntidadLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoEntidadLinkItemProvider atributoEntidadLinkItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoEntidadLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoEntidadLinkAdapter() {
		if (atributoEntidadLinkItemProvider == null) {
			atributoEntidadLinkItemProvider = new AtributoEntidadLinkItemProvider(this);
		}

		return atributoEntidadLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.LinkHerenciaPadre} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkHerenciaPadreItemProvider linkHerenciaPadreItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.LinkHerenciaPadre}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkHerenciaPadreAdapter() {
		if (linkHerenciaPadreItemProvider == null) {
			linkHerenciaPadreItemProvider = new LinkHerenciaPadreItemProvider(this);
		}

		return linkHerenciaPadreItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.LinkHerenciaHijo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkHerenciaHijoItemProvider linkHerenciaHijoItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.LinkHerenciaHijo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkHerenciaHijoAdapter() {
		if (linkHerenciaHijoItemProvider == null) {
			linkHerenciaHijoItemProvider = new LinkHerenciaHijoItemProvider(this);
		}

		return linkHerenciaHijoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.AtributoDerivadoEntidad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoDerivadoEntidadItemProvider atributoDerivadoEntidadItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.AtributoDerivadoEntidad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoDerivadoEntidadAdapter() {
		if (atributoDerivadoEntidadItemProvider == null) {
			atributoDerivadoEntidadItemProvider = new AtributoDerivadoEntidadItemProvider(this);
		}

		return atributoDerivadoEntidadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link modeloER.modeloER.RelacionAtributoLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionAtributoLinkItemProvider relacionAtributoLinkItemProvider;

	/**
	 * This creates an adapter for a {@link modeloER.modeloER.RelacionAtributoLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionAtributoLinkAdapter() {
		if (relacionAtributoLinkItemProvider == null) {
			relacionAtributoLinkItemProvider = new RelacionAtributoLinkItemProvider(this);
		}

		return relacionAtributoLinkItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (entidadItemProvider != null) entidadItemProvider.dispose();
		if (atributoItemProvider != null) atributoItemProvider.dispose();
		if (relacionItemProvider != null) relacionItemProvider.dispose();
		if (diagramaItemProvider != null) diagramaItemProvider.dispose();
		if (entidadRelacionItemProvider != null) entidadRelacionItemProvider.dispose();
		if (herenciaItemProvider != null) herenciaItemProvider.dispose();
		if (atributoDerivadoItemProvider != null) atributoDerivadoItemProvider.dispose();
		if (atributoMultivaluadoItemProvider != null) atributoMultivaluadoItemProvider.dispose();
		if (clavePrimariaItemProvider != null) clavePrimariaItemProvider.dispose();
		if (claveForaneaItemProvider != null) claveForaneaItemProvider.dispose();
		if (clavePrimariaForaneaItemProvider != null) clavePrimariaForaneaItemProvider.dispose();
		if (relacionTipoDebilItemProvider != null) relacionTipoDebilItemProvider.dispose();
		if (relacionTipoFuerteItemProvider != null) relacionTipoFuerteItemProvider.dispose();
		if (entidadRelacionDebilItemProvider != null) entidadRelacionDebilItemProvider.dispose();
		if (entidadRelacionFuerteItemProvider != null) entidadRelacionFuerteItemProvider.dispose();
		if (atributoDerivadoClavePrimariaItemProvider != null) atributoDerivadoClavePrimariaItemProvider.dispose();
		if (entidadFuerteItemProvider != null) entidadFuerteItemProvider.dispose();
		if (entidadDebilItemProvider != null) entidadDebilItemProvider.dispose();
		if (atributoSimpleItemProvider != null) atributoSimpleItemProvider.dispose();
		if (atributoCompuestoItemProvider != null) atributoCompuestoItemProvider.dispose();
		if (linkASACItemProvider != null) linkASACItemProvider.dispose();
		if (atributoEntidadLinkItemProvider != null) atributoEntidadLinkItemProvider.dispose();
		if (linkHerenciaPadreItemProvider != null) linkHerenciaPadreItemProvider.dispose();
		if (linkHerenciaHijoItemProvider != null) linkHerenciaHijoItemProvider.dispose();
		if (atributoDerivadoEntidadItemProvider != null) atributoDerivadoEntidadItemProvider.dispose();
		if (relacionAtributoLinkItemProvider != null) relacionAtributoLinkItemProvider.dispose();
	}

}
